<?php

/**
 * @file
 * Provides data for installation and removing module.
 */

/**
 * Implements hook_uninstall().
 *
 * Remove our variables after uninstall.
 */
function mappy_uninstall() {
  variable_del('mappy_google_width');
  variable_del('mappy_google_height');
  variable_del('mappy_yandex_width');
  variable_del('mappy_yandex_height');
  variable_del('mappy_load_pages_match');
  variable_del('mappy_load_pages_path');
}
